if (0) console.log('#1 zero is true')
if ("0") console.log('#2 zero is true')
if (null) console.log('null is true')
if (-1) console.log('negative is true')
if (1) console.log('postive is true')

// console.log(0)
// console.log("0")
// console.log(null)
// console.log(-1)
// console.log(1)  